# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cae6f33b7bf8d8e8647fc969da8daae3ef65b86372b26ab8d66f4cdc82d8e09105acc214cc84c24fdf474387a45c4088aeefb875000eb3afb6bb9b5533cfb338

test:
  secret_key_base: f90ab9f8dd3a7d26bf92cef27175e1ca0288d63cd0b5df5e1592bbdabe9b53d3aa90af1aa16659379c0347e92424a797d0347c58299e787e7c214fd4abea0044

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
